// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTjt5V3ldDLMfR7cf7SislRU6UoFF64pk',
    appId: '1:475629081253:web:2a3a3abc7b41fa9bd0334c',
    messagingSenderId: '475629081253',
    projectId: 'travel-app-f773b',
    authDomain: 'travel-app-f773b.firebaseapp.com',
    storageBucket: 'travel-app-f773b.firebasestorage.app',
    measurementId: 'G-6PBBJ5Z5WF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9d5JlLwO9lEtL-kMm1sv1QnIvygEYBws',
    appId: '1:475629081253:android:b827822358fdfc4cd0334c',
    messagingSenderId: '475629081253',
    projectId: 'travel-app-f773b',
    storageBucket: 'travel-app-f773b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZ8D3Lj7RE-yGhTlWrR_L0WbxjS8_MRB4',
    appId: '1:475629081253:ios:1fb918a594c39a95d0334c',
    messagingSenderId: '475629081253',
    projectId: 'travel-app-f773b',
    storageBucket: 'travel-app-f773b.firebasestorage.app',
    iosBundleId: 'com.example.travelApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZ8D3Lj7RE-yGhTlWrR_L0WbxjS8_MRB4',
    appId: '1:475629081253:ios:1fb918a594c39a95d0334c',
    messagingSenderId: '475629081253',
    projectId: 'travel-app-f773b',
    storageBucket: 'travel-app-f773b.firebasestorage.app',
    iosBundleId: 'com.example.travelApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCTjt5V3ldDLMfR7cf7SislRU6UoFF64pk',
    appId: '1:475629081253:web:5a9cf8b190e47c4bd0334c',
    messagingSenderId: '475629081253',
    projectId: 'travel-app-f773b',
    authDomain: 'travel-app-f773b.firebaseapp.com',
    storageBucket: 'travel-app-f773b.firebasestorage.app',
    measurementId: 'G-G6PQ9V21K4',
  );
}
